version: '3.9'

services:
    # Service Name
    filemanager:
        # Force container name
        container_name: filemanager
        
        # Associated Image
        image: filemanager:latest
        
        # Build Instructions
        build:
            context: .
            dockerfile: Dockerfile
        
        # Ports to be exposed (routing 8080 to 80)
        ports:
            - "8080:80"
        
        # Environment Variables
        environment:
            - RootDirectory=/data/root
            - UseHttpsRedirection=false
            - ASPNETCORE_ENVIRONMENT=Production
        
        # Mounted Volumes
        volumes:
            - "//c/Users/gameg/AppData/Roaming/PrismLauncher/instances/All the Mons - ATMons/minecraft:/data/root"

        # Restart Policy
        restart: unless-stopped
